version: 0.2

phases:
  build:
    commands:
      - mkdir -p build
      - rm -rf ./build/*
      - stack clean
      - stack build
      - cp `stack path --local-install-root`/bin/bootstrap build
      - cd build && zip function.zip bootstrap && rm bootstrap && cd -
artifacts:
  files:
    - "build/function.zip"
