name: newsletter
version: 0.1.0
github: "githubuser/newsletter"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2019 Author name here"

description: Please see the README on GitHub at <https://github.com/githubuser/newsletter#readme>

dependencies:
  - base >= 4.7 && < 5
  - aws-lambda-haskell-runtime >= 2.0.1
  - aeson
  - http-conduit
  - scientific >= 0.3.6
  - vector >= 0.12.0
  - amazonka
  - amazonka-core
  - amazonka-sqs
  - text >= 1.2.3
  - lens

library:
  source-dirs: src

executables:
  bootstrap:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -O2
      - -static
      - -with-rtsopts=-N
    cc-options: -static
    ld-options: -static -pthread
    dependencies:
      - newsletter

default-extensions:
  - TemplateHaskell
  - RecordWildCards
  - OverloadedLists
  - OverloadedStrings
  - DeriveGeneric
